version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    -
      image: circleci/node:8

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      -
        restore_cache:
          keys:
            - v0-dependencies-{{ checksum "yarn.lock" }}

      -
        run:
          name: Dependency Install
          command: yarn install

      -
        save_cache:
          paths:
            - node_modules
          key: v0-dependencies-{{ checksum "yarn.lock" }}

      # Run Tests!
      - run: npm test

      # Upload to CodeCov
      - run:
          name: 'Upload to codecov.io'
          command: bash <(curl -s https://codecov.io/bash) -t eddcd9b9-d6a1-4dfc-8a08-4115702686d6

      - store_artifacts:
          path: ./coverage

workflows:
  version: 2
  build_workflow:
    jobs:
      -
        test:
          filters:
            tags:
              only: /.*/
